# Generated by Django 5.0.2 on 2024-03-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_alter_session_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='uuid',
        ),
    ]
