# Generated by Django 5.0.2 on 2024-03-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Баллы'),
        ),
    ]
